FROM nginx:stable-alpine
# Copy the config and public files into the image
COPY ./default.conf /etc/nginx/conf.d/default.conf
# We can also bake the public files in!
COPY ../public /usr/share/nginx/html